# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

# 動作ok
#    - name: Heroku deploy
#      uses: akhileshns/heroku-deploy@v3.8.8
#      with:
#        heroku_api_key: "51ed0720-fb88-4bdd-a7a5-6e1df5b61884"
#        heroku_app_name: "owasp-zap-test-target"
#        heroku_email: "tetsuhiko.takahashi.zp@hitachi.com"

# 動作ok
#    - name: ZAP Scan
#      uses: zaproxy/action-full-scan@v0.3.0
#      with:
#        target: 'https://owasp-zap-test-target.herokuapp.com/'
#        cmd_options: >
#           -a
#           -j
#           -z "
#           -config alert.maxInstances=0
#           -config view.locale=ja_JP
#           "

# 動作確認途中
#    - name: OpenVAS Scan
#      run: |
#       docker run -d -p 443:443 --name openvas mikesplain/openvas
#       docker top openvas

# 動作ok
#    - name: nmap Scan
#      run: |
#       sudo apt install nmap -y
#       nmap -A localhost
       
    - name: Create Issue
      run: |
       hub issue -h
       #hub issue create -l bot -m 'test issue created!' -F ./result.txt
       hub issue create -l bot -m ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
