# This is a basic workflow to help you get started with Actions

name: Zap-Advanced-Scan

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "zap_scan"
  zap_scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Scan SIOS test site
    steps:
      - name: ZAP Scan test.sios.com
        uses: zaproxy/action-baseline@v0.3.0
        with:
          target: 'https://owasp-zap-test-target.herokuapp.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          
